services:
  - type: web
    name: valderrama-school
    env: node
    rootDir: V2
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
